---
Name: Heyday Elastica Config
---
SilverStripe\Core\Injector\Injector:
  Heyday\Elastica\ReindexTask:
    constructor:
      - %$Heyday\Elastica\ElasticaService
  Heyday\Elastica\Searchable:
    constructor:
      - %$Heyday\Elastica\ElasticaService
  ManyManyList:
    class: Heyday\Elastica\ManyManyList

Symbiote\QueuedJobs\Jobs\CleanupJob:
  is_enabled: true